cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - mem_mb=1000
jobs: 1
printshellcmds: True
