import snakemake.utils

snakemake.utils.min_version("7.0.0")


rule all:
    input:
        expand("output/{iteration}.txt", iteration=range(100)),


rule sleeper:
    output:
        "output/{iteration}.txt",
    shell:
        """
        sleep 180s
        touch {output}
        """
