n = 5


rule all:
    input:
        expand("output/rule3-{rep}.txt", rep=range(1, n + 1)),


rule rule1:
    output:
        "output/rule1-{rep}.txt",
    shell:
        "touch {output}"


rule rule2:
    input:
        "output/rule1-{rep}.txt",
    output:
        "output/rule2-{rep}.txt",
    resources:
        mem_mb=4000,
    shell:
        "touch {output}"


rule rule3:
    input:
        "output/rule2-{rep}.txt",
    output:
        "output/rule3-{rep}.txt",
    shell:
        "touch {output}"
