cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
jobs: 10
printshellcmds: True
software-deployment-method: conda
