rule all:
    input:
        "output/default-memory.txt",
        "output/rule-specific-memory.txt",
        "output/dynamic-resources.txt",


rule default_mem:
    output:
        "output/default-memory.txt",
    shell:
        """
        sleep 10s
        sacct --units G --format JobName,State,Elapsed,REQMEM,MaxRSS -j $SLURM_JOB_ID
        mem=`sacct --units G --format REQMEM -j $SLURM_JOB_ID | tail -n 1`
        echo "Requested memory: $mem"
        echo "$mem" > {output}
        """


rule rule_specific_mem:
    output:
        "output/rule-specific-memory.txt",
    resources:
        mem_gb=8,
    shell:
        """
        sleep 10s
        sacct --units G --format JobName,State,Elapsed,REQMEM,MaxRSS -j $SLURM_JOB_ID
        mem=`sacct --units G --format REQMEM -j $SLURM_JOB_ID | tail -n 1`
        echo "Requested memory: $mem"
        echo "$mem" > {output}
        """


rule dynamic_resources:
    output:
        "output/dynamic-resources.txt",
    resources:
        mem_gb=lambda _, attempt: 1 + ((attempt - 1) * 2),
    shell:
        """
        sleep 1s
        sacct --units G --format JobName,State,Elapsed,REQMEM,MaxRSS -j $SLURM_JOB_ID
        mem=`sacct --units G --format REQMEM -j $SLURM_JOB_ID | tail -n 1`
        echo "Requested memory: $mem"
        exit 1
        """
