cluster-generic-submit-cmd:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule} &&
  sbatch
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - mem_mb=1000
jobs: 500
printshellcmds: True
