FROM rocker/r-edge
RUN apt-get update -qq && apt-get -y --no-install-recommends install \
  libxml2-dev \
  libsqlite-dev \
  libssh2-1-dev \
  libcurl4-openssl-dev \
  bcftools \
  libssl-dev \
  r-cran-tidyverse \