rule all:
    input:
        "output/default.txt",


rule singularity_tmp_default:
    output:
        "output/default.txt",
    container:
        "docker://rocker/r-edge:4.1.0",
    shell:
        """
        $tmpf = $(mktemp)
        echo This rule created the file $tmpf in $TMPDIR > {output}
        shuf -i 100 > $tmpf
        cat $tmpf >> {output}
        R -e 'sessionInfo()' >> {output}
        """
