---
cluster:
  sbatch
    {resources.partitionFlag}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partitionFlag=""
  - qos=<name-of-quality-of-service>
  - mem_mb=1000
